import { prismaObjectType } from "nexus-prisma";
import { createUser, updateUser} from "./user/user-resolvers";
import { createBill, updateBill} from "./bill/bill-resolvers";
import {createTransaction, updateTransaction} from "./transaction/transaction-resolvers";

import userDefs from './users';

const entityNames = [user, bill];

entityNames.forEach(entityName => {
    const entitydefs = require('./)
})

// @ts-ignore
export const Mutation = prismaObjectType({
    name: "Mutation",
    definition(t) {
        // t.prismaFields(["*"]); expose all the mutations generated by prisma
        createUser(t);
        updateUser(t);
        createBill(t);
        updateBill(t);
        createTransaction(t);
        updateTransaction(t);
    },
});
